# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AiTerminal < Formula
  desc "AI driven development in your terminal"
  homepage "https://github.com/coding-hui/ai-terminal"
  version "0.13.7"

  on_macos do
    on_intel do
      url "https://github.com/coding-hui/ai-terminal/releases/download/v0.13.7/ai-terminal_Darwin_x86_64.tar.gz"
      sha256 "6e9082c7c15236b7386ff2a9fa8f0bc333fbd451e637744ebe84b349b8bd6833"

      def install
        bin.install "ai"
        bash_completion.install "completions/ai-terminal.bash" => "ai-terminal"
        zsh_completion.install "completions/ai-terminal.zsh" => "_ai-terminal"
        fish_completion.install "completions/ai-terminal.fish"
        man1.install "manpages/ai-terminal.1.gz"
      end
    end
    on_arm do
      url "https://github.com/coding-hui/ai-terminal/releases/download/v0.13.7/ai-terminal_Darwin_arm64.tar.gz"
      sha256 "c590f110d84e9efbc46babb305c2e3d427cdb4a6de6d97a01d326eb2fddcf1be"

      def install
        bin.install "ai"
        bash_completion.install "completions/ai-terminal.bash" => "ai-terminal"
        zsh_completion.install "completions/ai-terminal.zsh" => "_ai-terminal"
        fish_completion.install "completions/ai-terminal.fish"
        man1.install "manpages/ai-terminal.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/coding-hui/ai-terminal/releases/download/v0.13.7/ai-terminal_Linux_x86_64.tar.gz"
        sha256 "904843cff5c5d4d6e6ace94ea05ea8548d65ff980e124c2e8fffbea27c89ab8c"

        def install
          bin.install "ai"
          bash_completion.install "completions/ai-terminal.bash" => "ai-terminal"
          zsh_completion.install "completions/ai-terminal.zsh" => "_ai-terminal"
          fish_completion.install "completions/ai-terminal.fish"
          man1.install "manpages/ai-terminal.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/coding-hui/ai-terminal/releases/download/v0.13.7/ai-terminal_Linux_arm64.tar.gz"
        sha256 "687594a5245710a011ff50e6d6de6ae7791b509c2815ff6a53828d0a80d3448c"

        def install
          bin.install "ai"
          bash_completion.install "completions/ai-terminal.bash" => "ai-terminal"
          zsh_completion.install "completions/ai-terminal.zsh" => "_ai-terminal"
          fish_completion.install "completions/ai-terminal.fish"
          man1.install "manpages/ai-terminal.1.gz"
        end
      end
    end
  end
end
