# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AiTerminal < Formula
  desc "AI driven development in your terminal"
  homepage "https://github.com/coding-hui/ai-terminal"
  version "0.13.6"

  on_macos do
    on_intel do
      url "https://github.com/coding-hui/ai-terminal/releases/download/v0.13.6/ai-terminal_Darwin_x86_64.tar.gz"
      sha256 "3bea9d75a1448cee0caa18dc9dc9bf6d4c35149300cc792fa4c90b84bd32750c"

      def install
        bin.install "ai"
        bash_completion.install "completions/ai-terminal.bash" => "ai-terminal"
        zsh_completion.install "completions/ai-terminal.zsh" => "_ai-terminal"
        fish_completion.install "completions/ai-terminal.fish"
        man1.install "manpages/ai-terminal.1.gz"
      end
    end
    on_arm do
      url "https://github.com/coding-hui/ai-terminal/releases/download/v0.13.6/ai-terminal_Darwin_arm64.tar.gz"
      sha256 "ad98e910c68b4fcfbf626f1e8b3aec265f9759c34d2eb75117cc5d26d6f0de58"

      def install
        bin.install "ai"
        bash_completion.install "completions/ai-terminal.bash" => "ai-terminal"
        zsh_completion.install "completions/ai-terminal.zsh" => "_ai-terminal"
        fish_completion.install "completions/ai-terminal.fish"
        man1.install "manpages/ai-terminal.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/coding-hui/ai-terminal/releases/download/v0.13.6/ai-terminal_Linux_x86_64.tar.gz"
        sha256 "0ca3fd028b301af37cb93e27217f65c254cb6e1bb9f7db6ae2e99455b8db9170"

        def install
          bin.install "ai"
          bash_completion.install "completions/ai-terminal.bash" => "ai-terminal"
          zsh_completion.install "completions/ai-terminal.zsh" => "_ai-terminal"
          fish_completion.install "completions/ai-terminal.fish"
          man1.install "manpages/ai-terminal.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/coding-hui/ai-terminal/releases/download/v0.13.6/ai-terminal_Linux_arm64.tar.gz"
        sha256 "d61b843e5bc9735fe1b8fcd8029b2d544bdbc499ecbe1995689b633c7f39f8ad"

        def install
          bin.install "ai"
          bash_completion.install "completions/ai-terminal.bash" => "ai-terminal"
          zsh_completion.install "completions/ai-terminal.zsh" => "_ai-terminal"
          fish_completion.install "completions/ai-terminal.fish"
          man1.install "manpages/ai-terminal.1.gz"
        end
      end
    end
  end
end
