# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AiTerminal < Formula
  desc "AI driven development in your terminal"
  homepage "https://github.com/coding-hui/ai-terminal"
  version "0.13.8"

  on_macos do
    on_intel do
      url "https://github.com/coding-hui/ai-terminal/releases/download/v0.13.8/ai-terminal_Darwin_x86_64.tar.gz"
      sha256 "b69ec73a4ad092a7c154c64337a1f874ebac5d60037fe8a47d8a6899721c7d80"

      def install
        bin.install "ai"
        bash_completion.install "completions/ai-terminal.bash" => "ai-terminal"
        zsh_completion.install "completions/ai-terminal.zsh" => "_ai-terminal"
        fish_completion.install "completions/ai-terminal.fish"
        man1.install "manpages/ai-terminal.1.gz"
      end
    end
    on_arm do
      url "https://github.com/coding-hui/ai-terminal/releases/download/v0.13.8/ai-terminal_Darwin_arm64.tar.gz"
      sha256 "341e7254edc146f6eb310a05f88c7fcd5e876c418776965176fa980a0ed90a89"

      def install
        bin.install "ai"
        bash_completion.install "completions/ai-terminal.bash" => "ai-terminal"
        zsh_completion.install "completions/ai-terminal.zsh" => "_ai-terminal"
        fish_completion.install "completions/ai-terminal.fish"
        man1.install "manpages/ai-terminal.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/coding-hui/ai-terminal/releases/download/v0.13.8/ai-terminal_Linux_x86_64.tar.gz"
        sha256 "6b0406c5ccaa1e24a71f5bfb6b60ea649c9937cdc5f9bbb5f0e8e7bebfd5f94e"

        def install
          bin.install "ai"
          bash_completion.install "completions/ai-terminal.bash" => "ai-terminal"
          zsh_completion.install "completions/ai-terminal.zsh" => "_ai-terminal"
          fish_completion.install "completions/ai-terminal.fish"
          man1.install "manpages/ai-terminal.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/coding-hui/ai-terminal/releases/download/v0.13.8/ai-terminal_Linux_arm64.tar.gz"
        sha256 "fa1cd20bd63293a6a616307504093e992ff8b06bea9ccd05cb9b88451dddb13a"

        def install
          bin.install "ai"
          bash_completion.install "completions/ai-terminal.bash" => "ai-terminal"
          zsh_completion.install "completions/ai-terminal.zsh" => "_ai-terminal"
          fish_completion.install "completions/ai-terminal.fish"
          man1.install "manpages/ai-terminal.1.gz"
        end
      end
    end
  end
end
