# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NasCloud < Formula
  desc "Self-hosted home NAS: storage, photos, WebDAV and restic backups in one binary"
  homepage "https://github.com/coding-hui/nas-cloud"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/coding-hui/nas-cloud/releases/download/v0.1.0/nas-cloud_Darwin_x86_64.tar.gz"
      sha256 "e2fe3d1f9b3aec1ad6a7728c3f16aed27542f6d2dbaa6158297f04e04951d68e"

      define_method(:install) do
        bin.install "nas-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/coding-hui/nas-cloud/releases/download/v0.1.0/nas-cloud_Darwin_arm64.tar.gz"
      sha256 "7eb9d5ff700006e99ef6db1d46048e297b60755b975c6d94b6ca003dfaada8ea"

      define_method(:install) do
        bin.install "nas-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/coding-hui/nas-cloud/releases/download/v0.1.0/nas-cloud_Linux_x86_64.tar.gz"
      sha256 "6dc2ae0612cf3d315b74e52df820388fbe1b850f4e59e8c24eccb9cb5e8ace01"
      define_method(:install) do
        bin.install "nas-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/coding-hui/nas-cloud/releases/download/v0.1.0/nas-cloud_Linux_arm64.tar.gz"
      sha256 "8ee453be8a86f90b27f9da123ceb0a7699c2996e09ff5de5947b34a6f9848101"
      define_method(:install) do
        bin.install "nas-server"
      end
    end
  end
end
